data = [
    {
        "name": "iPhone 15 Pro",
        "price": 346,
        "description": "Flagship smartphone",
        "brand": "Apple",
    },
    {
        "name": "Galaxy S25 Ultra",
        "price": 215,
        "description": "Premium Android phone",
        "brand": "Samsung",
    },
    {
        "name": "Xiaomi 14 Ultra",
        "price": 183,
        "description": "High-end performance",
        "brand": "Xiaomi",
    },
    {
        "name": "Galaxy Watch 6",
        "price": 181,
        "description": "Smart fitness watch",
        "brand": "Samsung",
    },
    {
        "name": "Redmi Note 13 Pro",
        "price": 174,
        "description": "Affordable flagship",
        "brand": "Xiaomi",
    },
    {
        "name": "Apple Watch SE",
        "price": 172,
        "description": "Smartwatch with style",
        "brand": "Apple",
    },
    {
        "name": "Galaxy Z Fold5",
        "price": 167,
        "description": "Foldable smartphone",
        "brand": "Samsung",
    },
    {
        "name": "POCO X6 Pro",
        "price": 149,
        "description": "Gaming on budget",
        "brand": "POCO",
    },
    {
        "name": "iPad Air M2",
        "price": 145,
        "description": "Powerful lightweight tablet",
        "brand": "Apple",
    },
    {
        "name": "Galaxy A55",
        "price": 138,
        "description": "Mid-range smartphone",
        "brand": "Samsung",
    },
    {
        "name": "Xiaomi Pad 6",
        "price": 135,
        "description": "Tablet for entertainment",
        "brand": "Xiaomi",
    },
    {
        "name": "MacBook Air M3",
        "price": 133,
        "description": "Ultra-thin laptop",
        "brand": "Apple",
    },
    {
        "name": "Galaxy Tab S9",
        "price": 131,
        "description": "Android productivity tablet",
        "brand": "Samsung",
    },
    {
        "name": "Nothing Phone (2)",
        "price": 127,
        "description": "Stylish transparent phone",
        "brand": "Nothing",
    },
    {
        "name": "Sony WH-1000XM5",
        "price": 119,
        "description": "Noise-canceling headphones",
        "brand": "Sony",
    },
    {
        "name": "Beats Studio Pro",
        "price": 113,
        "description": "Wireless noise-canceling",
        "brand": "Apple",
    },
    {
        "name": "Nike Smartband",
        "price": 109,
        "description": "Fitness tracking band",
        "brand": "Nike",
    },
    {
        "name": "Huawei Watch GT 4",
        "price": 108,
        "description": "Long battery smartwatch",
        "brand": "Huawei",
    },
    {
        "name": "Lenovo Legion Phone",
        "price": 107,
        "description": "Gaming beast",
        "brand": "Lenovo",
    },
    {
        "name": "Pixel 8 Pro",
        "price": 94,
        "description": "Google flagship phone",
        "brand": "Google",
    },
    {
        "name": "Oppo Find X7",
        "price": 90,
        "description": "Elegant phone with zoom",
        "brand": "Oppo",
    },
    {
        "name": "ROG Phone 8",
        "price": 89,
        "description": "Ultimate gaming phone",
        "brand": "ASUS",
    },
    {
        "name": "realme GT Neo 6",
        "price": 87,
        "description": "Fast and affordable",
        "brand": "realme",
    },
    {
        "name": "Realme Pad X",
        "price": 86,
        "description": "Budget Android tablet",
        "brand": "realme",
    },
    {
        "name": "Xiaomi Pad 5",
        "price": 85,
        "description": "Balanced budget tablet",
        "brand": "Xiaomi",
    },
    {
        "name": "Huawei Mate 60 Pro",
        "price": 81,
        "description": "Flagship with HarmonyOS",
        "brand": "Huawei",
    },
    {
        "name": "Vivo V30 Pro",
        "price": 80,
        "description": "Photography smartphone",
        "brand": "Vivo",
    },
    {
        "name": "Victoria Smart Mirror",
        "price": 69,
        "description": "Smart beauty mirror",
        "brand": "Victoria’s Secret",
    },
    {
        "name": "ASUS Zenfone 10",
        "price": 68,
        "description": "Compact and powerful",
        "brand": "ASUS",
    },
    {
        "name": "Motorola Edge 40 Pro",
        "price": 66,
        "description": "Sleek and fast",
        "brand": "Motorola",
    },
    {
        "name": "Honor Magic6 Pro",
        "price": 65,
        "description": "AI-powered smartphone",
        "brand": "Honor",
    },
    {
        "name": "Sony Xperia 1 V",
        "price": 64,
        "description": "Pro photography phone",
        "brand": "Sony",
    },
    {
        "name": "OnePlus 12",
        "price": 63,
        "description": "Fast and smooth",
        "brand": "OnePlus",
    },
    {
        "name": "ZTE Nubia Red Magic 9",
        "price": 62,
        "description": "Gaming phone with fan",
        "brand": "ZTE",
    },
    {
        "name": "Infinix Zero 30",
        "price": 67,
        "description": "Budget vlogging phone",
        "brand": "Infinix",
    },
    {
        "name": "Nokia X30 5G",
        "price": 82,
        "description": "Eco-friendly 5G phone",
        "brand": "Nokia",
    },
    {
        "name": "Beats Fit Pro",
        "price": 61,
        "description": "Workout-friendly earbuds",
        "brand": "Apple",
    },
    {
        "name": "HTC VIVE XR Elite",
        "price": 59,
        "description": "Immersive VR headset",
        "brand": "HTC",
    },
    {
        "name": "PlayStation Portal",
        "price": 58,
        "description": "Remote Play handheld",
        "brand": "Sony",
    },
    {
        "name": "DJI Mini 4 Pro",
        "price": 56,
        "description": "Compact drone camera",
        "brand": "DJI",
    },
    {
        "name": "Kindle Paperwhite",
        "price": 56,
        "description": "E-reader with backlight",
        "brand": "Amazon",
    },
    {
        "name": "Logitech MX Master 3S",
        "price": 57,
        "description": "Precision productivity mouse",
        "brand": "Logitech",
    },
    {
        "name": "boAt Wave Sigma",
        "price": 55,
        "description": "Affordable smartwatch",
        "brand": "boAt",
    },
    {
        "name": "realme Buds Air 5",
        "price": 54,
        "description": "Wireless earbuds with ANC",
        "brand": "realme",
    },
    {
        "name": "Noise ColorFit Ultra 3",
        "price": 53,
        "description": "Stylish budget smartwatch",
        "brand": "Noise",
    },
    {
        "name": "RedMagic Keyboard",
        "price": 52,
        "description": "RGB mechanical keyboard",
        "brand": "RedMagic",
    },
    {
        "name": "Xiaomi Smart Camera C300",
        "price": 51,
        "description": "360° home surveillance",
        "brand": "Xiaomi",
    },
    {
        "name": "Soundcore Liberty 4",
        "price": 50,
        "description": "Hi-res true wireless earbuds",
        "brand": "Anker",
    },
    {
        "name": "JBL Tune Flex",
        "price": 49,
        "description": "Bass-rich wireless earbuds",
        "brand": "JBL",
    },
    {
        "name": "Spalding Smart Basketball",
        "price": 47,
        "description": "Sensor-equipped basketball",
        "brand": "Spalding",
    },
]
